export const EDUCATION_ENUM = [
  "undergraduate",
  "graduate",
  "masters",
  "phd",
  "10th",
  "other",
  "none",
];
export const MARITAL_STATUS_ENUM = [
  "single",
  "married",
  "divorced",
  "widowed",
  "other",
];
export const ASSETS_ENUM = ["car", "house", "land", "other", "none"];
export const PROFESSION_ENUM = ["job", "student", "business", "other", "none"];
export const INCOME_ENUM = [
  "< 5l",
  "5l to 10l",
  "10l to 15l",
  "15l to 25l",
  "> 25l",
  "nil",
];
export const GENDER_ENUM = ["male", "female"];
export const RELIGION_ENUM = ["hindu", "christian", "muslim", "other"];
export const VERIFICATION_STATUS_ENUM = [
  "unverified",
  "pending",
  "verified",
  "visited",
  "blocked",
  "deleted",
];
export const GOTRAM_ENUM = [
  "akramulakula",
  "akyamulakula",
  "amalakula",
  "arkyamula",
  "anubha gula",
  "anubala",
  "anubala gula",
  "arasakula",
  "arisishtakula",
  "elisishtakula",
  "arisetlakula",
  "harisishtakula",
  "yanasakula",
  "yaanasakakula",
  "yaanasabikula",
  "balasishta",
  "balaseshta",
  "balisishta",
  "balisetla",
  "pruthivisishta",
  "pruthivisreshta",
  "bhudhikula",
  "brahmkula",
  "bhdhanakula",
  "dhurvadikula",
  "dhulaasishtakula",
  "dhuryadakula",
  "dhulasishtakula",
  "dhulasikula",
  "dhodakula",
  "desetla",
  "dhodilula",
  "perusishta",
  "berisishtakula",
  "bhyrusishtakula",
  "chakramulakula",
  "chaturbela",
  "csreelakula",
  "chakramulasakula",
  "bethashreshta",
  "bethakishta",
  "pathasishtakula",
  "pathtasishtakula",
  "ilamanchikula",
  "yalamanchikula",
  "helamanchikula",
  "kamalakula",
  "dhrugasishta",
  "dhrugasishtakula",
  "thanathakula",
  "chaanakalakula",
  "chownaka",
  "usirakula",
  "dhesishtakula",
  "haaraasikula",
  "thithisa",
  "thithinakula",
  "thenthsula",
  "thenthasala",
  "thethanakula",
  "sarakula",
  "sekotlakula",
  "segolla",
  "samanakula",
  "shreshta kundala kula",
  "garnakula",
  "praheenukula",
  "praheenikula",
  "paipikula",
  "injthapakula",
  "gopakula",
  "kondakula",
  "kondakakula",
  "kamasishta",
  "ganthiseela",
  "ganthaseelakula",
  "ganthaseela",
  "granthiseela",
  "esabakula",
  "esubakula",
  "eshubakula",
  "sannakula",
  "janakula",
  "jyanukula",
  "ishvaku kula",
  "kapata",
  "kurata",
  "koratakula",
  "gorantakula",
  "sirisishtakula",
  "sirasishtakula",
  "kundakula",
  "dhurasishta",
  "dhurasishtakula",
  "chandrakula",
  "chandramoola",
  "chandramasishta",
  "thrimula",
  "thrimulakula",
  "santhakula",
  "janakula",
  "jyanukula",
  "burhtilasishakula",
  "brumasishtakula",
  "lruthtikula",
  "venkalakula",
  "mandu",
  "mandhakula",
  "hasthakula",
  "mandakula",
  "ganamuku kula",
  "kanalola",
  "kanasrila",
  "kanasrila kula",
  "karakapala",
  "dhanakula",
  "thananakula",
  "thenukula",
  "mathyakula",
  "manyukula",
  "maraasakula",
  "maanaachakula",
  "monukula",
  "moruka",
  "morusa",
  "murkula",
  "mathtikula",
  "mathanakula",
  "mathyasakula",
  "mithunakula",
  "maithrikula",
  "vinnasa",
  "vinnakula",
  "vinukula",
  "vennakula",
  "thishamasishtakula",
  "theeshmakula",
  "theeshmasishtakula",
  "theeshmashreshta",
  "munjeekula",
  "mounjrisa",
  "mounjikula",
  "naabilla",
  "naabeelakula",
  "naabeelasakula",
  "munikula",
  "moolakula",
  "padmasishtasa",
  "padmasishtakula",
  "padmashreshta",
  "palakakula",
  "palakula",
  "pamdikula",
  "sandhoku",
  "sandhokulakula",
  "kamathenukula",
  "patakaseelakula",
  "panchalakula",
  "panchallakula",
  "pranaseelakula",
  "pranuseelakula",
  "prana seela kula",
  "papaala",
  "kanapakula",
  "kantakula",
  "kantaasukula",
  "kantasuukula",
  "kantasthulakula",
  "sanasishta",
  "sanasishtakula",
  "sinishetla",
  "dhuvvisishtakula",
  "poulathathsya kula",
  "sribhumsikula",
  "dhayasishtakula",
  "dhayaa sishtakula",
  "dhasishtakula",
  "thaisettakula",
  "thesetlakula",
  "thesishtakula",
  "thysishtakula",
  "ayanakula",
  "goseela",
  "uthamagoseela",
  "pallalagooseela",
  "padugoseela",
  "srigoseela",
  "punagoseela",
  "sooryakula",
  "uthamaseela",
  "punagorseela",
  "pattugoseela",
  "punakaseelakula bheemagoseela",
  "sathyagoseela",
  "chandhigoseela",
  "ponagshila",
  "bumsimamsukula",
  "bumsimanakula",
  "brosishtakula",
  "brosi",
  "brolekakula",
  "udhvahakula",
  "pendlikula",
  "ravisishtakula",
  "vanisishtakula",
  "lenasishtakula",
  "lelisishtakula",
  "anusishta",
  "anusishtakula",
  "kranukula",
  "thondikula",
  "ananthakula",
  "kundakakula",
  "kondakakula",
  "rendukula",
  "rentakula",
  "shanakula",
  "sanakula",
  "samasishtakula",
  "dankarakula",
  "muthukula",
  "kramasishta",
  "kramasishtakula",
  "kramashreshtakula",
  "anthirakula",
  "chinthakula",
  "chinthamasishta",
  "chinthyakula",
  "chinthala",
  "thuppalakula",
  "srisalakula",
  "srisalla",
  "srisallakula",
  "puthurukula",
  "puthuruksakula",
  "hasthikula",
  "chusalakula",
  "sakallakula",
  "soochalakula",
  "sookasallakula",
  "soosalakula",
  "sirisheshta",
  "sirisheshtakula",
  "srishi",
  "silakula",
  "srirangakula",
  "other" /* for other gotrams */,
];
export const CASTE_ENUM = {
  brahmin: ["saiva", "aacharya", "niyoogi"],
  kamma: ["pedda", "bangāru", "chowdary", "nāidu"],
  kaapu: ["telaga", "munnuru kapu", "turpu kapu"],
  komati: ["vysya", "kalinga"],
  reddy: ["ganta"],
  yadav: ["golla", "yadava"],
  other: ["other"],
};

export const RAASI_ENUM = [
  "mesha",
  "vrishabha",
  "mithuna",
  "karka",
  "simha",
  "kanya",
  "tula",
  "vrishchika",
  "Dhanu",
  "Makara",
  "Kumbha",
  "Meena",
];
export const NAKSHATRAM_ENUM = [
  "ashwini",
  "bharani",
  "krittika",
  "rohini",
  "mrigashira",
  "ardra",
  "punarvasu",
  "pushya",
  "ashlesha",
  "magha",
  "purva phalguni",
  "uttara phalguni",
  "hasta",
  "chitra",
  "swati",
  "vishaka",
  "anuradha",
  "jyeshta",
  "mula",
  "poorva ashadha",
  "uttara ashadha",
  "shravana",
  "dhanishtha",
  "shatabhisha",
  "purva bhadrapada",
  "uttara bhadrapada",
  "revati",
  "abhijit",
];
