export const EDUCATION_ENUM = [
  "undergraduate",
  "graduate",
  "masters",
  "phd",
  "10th",
  "other",
  "none",
];
export const MARITAL_STATUS_ENUM = [
  "single",
  "married",
  "divorced",
  "widowed",
  "other",
];
export const ASSETS_ENUM = ["car", "house", "land", "other", "none"];
export const PROFESSION_ENUM = ["job", "student", "business", "other", "none"];
export const INCOME_ENUM = [
  "< 5l",
  "5l to 10l",
  "10l to 15l",
  "15l to 25l",
  "> 25l",
  "nil",
];
export const RELIGION_ENUM = ["hindu", "christian", "muslim", "other"];
export const VERIFIED_ENUM = [
  "not verified",
  "pending",
  "verified",
  "visited",
  "blocked",
  "deleted",
];
export const GOTRAM_ENUM = [
  "achayanasa",
  "agasthyasa",
  "athreyasa",
  "aushithyasa",
  "bharadhvajasa",
  "bhargavasa",
  "bhodhayanasa",
  "bhoodhi mashasa",
  "bruhathathvasa",
  "chakrapanisa",
  "chamarshanasa",
  "chowcheyasa",
  "chownakasa",
  "dheva kalkyasa",
  "dhevarathasa",
  "dhurvasasa",
  "gandharpasa",
  "ganvsa",
  "garkyasa",
  "gopakasa",
  "goundheyasa",
  "gouthamasa",
  "gruthsan mathasa",
  "guthsasa",
  "harivalgayasa",
  "jabaalisa",
  "jadabarathasa",
  "jadhukarnasa",
  "jambasoothanasa",
  "jarathkarasa",
  "jeevandhisa",
  "kabeedhasa",
  "kabilasa",
  "kasyabasa",
  "koundinyasa",
  "kousikasa",
  "krushnasa",
  "maanavasa",
  "maarkandeyasa",
  "maithreyasa",
  "manthapalasa",
  "mareechasa",
  "mounjaya",
  "mouthkalyasa",
  "munirajasa",
  "naradhasa",
  "nethra pahtasa",
  "paaraasaryasa",
  "pallavasa",
  "papreyasa",
  "paras paraayanyasa",
  "pavithra paanisa",
  "pingalasa",
  "poulasthyasa",
  "poundrakasa",
  "prabhadhasa",
  "praseenasa",
  "pundareegasa",
  "rushyashrungasa",
  "saargnaravasa",
  "samvarthakasa",
  "sanakasa",
  "sananthanasa",
  "sanathkumarasa",
  "sarabankasa",
  "sathyasa",
  "shandilyasa",
  "shuklasa",
  "sowbarnasa",
  "sowmyasa",
  "sowvarnasa",
  "sridharasa",
  "srivathsasa",
  "subhramhanyasa",
  "sudheeshanasa",
  "sukanchanasa",
  "sundharasa",
  "suvarnasa",
  "thaithreyasa",
  "thalpyasa",
  "tharanisa",
  "thithirisa",
  "thoumyasa",
  "thrijadasa",
  "udhgrushtasa",
  "ugrasenasa",
  "uthamojasa",
  "vadugasa",
  "vairohithyasa",
  "valmikasa",
  "vamadevasa",
  "varadhanthusa",
  "varunasa",
  "vashishtasa",
  "vasudevasa",
  "vayavyaya",
  "vishnuvrunthasa",
  "vishvagshenasa",
  "visvamithrasa",
  "vyasasa",
  "yaaskasa",
  "yagna valkyasa",
  "other" /* for other gotrams */,
];
export const CASTE_ENUM = {
  brahmin: ["saiva", "aacharya", "niyoogi"],
  kamma: ["pedda", "bangāru", "chowdary", "nāidu"],
  kaapu: ["telaga", "munnuru kapu", "turpu kapu"],
  komati: ["vysya", "kalinga"],
  reddy: ["ganta"],
  yadav: ["golla", "yadava"],
  other: ["other"],
};
export const GENDER_ENUM = ["male", "female"];
